server:
  port: 8082

---
#eureka:
#
#  instance:
#    instance-id: product-microservice-instance
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/virspit_product
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties.hibernate.format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data.web.pageable.max-page-size: 100

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: aws.yongwoonlim.com:9092
      group-id: product_group
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: aws.yongwoonlim.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    product: product
    order: order

file.dir: C:/Users/yongwoon/file/